/*******************************************************************************
 * Copyright (c) 2021 Eclipse RDF4J contributors.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *******************************************************************************/
// Some portions generated by Co-Pilot
package org.eclipse.rdf4j.sail.lmdb;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.util.Random;

import org.eclipse.rdf4j.sail.lmdb.TxnManager.Txn;
import org.eclipse.rdf4j.sail.lmdb.config.LmdbStoreConfig;
import org.eclipse.rdf4j.sail.lmdb.model.LmdbValue;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Low-level tests for {@link TripleStore}.
 */
public class CardinalityTest {
	@TempDir
	File tempFolder;

	private File dataDir;

	protected TripleStore tripleStore;

	@BeforeEach
	public void before() throws Exception {
		dataDir = new File(tempFolder, "triplestore");
		dataDir.mkdir();
		tripleStore = new TripleStore(dataDir, new LmdbStoreConfig("spoc,posc,ospc"), null);
	}

	int count(RecordIterator it) {
		int count = 0;
		while (it.next() != null) {
			count++;
		}
		return count;
	}

	@Test
	public void testCardinalityForFullyBoundPattern() throws Exception {
		tripleStore.startTransaction();
		tripleStore.storeTriple(11, 22, 33, 44, true);
		tripleStore.commit();

		double estimated = tripleStore.cardinality(11, 22, 33, 44);

		assertEquals(1.0, estimated, 0.0001, "Fully bound pattern should include the exact key");
	}

	@Test
	public void testCardinalityIncludesInferredWhenExplicitIsEmpty() throws Exception {
		tripleStore.startTransaction();
		tripleStore.storeTriple(100, 2, 300, 1, false);
		tripleStore.commit();

		double estimated = tripleStore.cardinality(LmdbValue.UNKNOWN_ID, 2, LmdbValue.UNKNOWN_ID, 1);

		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			double expected = count(tripleStore.getTriples(txn, LmdbValue.UNKNOWN_ID, 2, LmdbValue.UNKNOWN_ID, 1, true))
					+ count(tripleStore.getTriples(txn, LmdbValue.UNKNOWN_ID, 2, LmdbValue.UNKNOWN_ID, 1, false));
			assertEquals(expected, estimated, 0.0001, "Cardinality should include inferred entries");
		}
	}

	void assertInRange(double a, double b, double toleranceRatio) {
		System.out.println("Expected " + a + " to be within " + (toleranceRatio * 100) + "% of " + b);
		assertTrue(Math.abs(a - b) <= toleranceRatio * Math.abs(b),
				"Expected " + a + " to be within " + (toleranceRatio * 100) + "% of " + b);
	}

	@Test
	public void testCardinalities() throws Exception {
		Random random = new Random(1337);

		int nrOfResources = 100;

		tripleStore.startTransaction();
		for (int resource = 1; resource <= nrOfResources; resource++) {
			int nrOfTriples = 100 + random.nextInt(900);
			for (int i = 0; i < nrOfTriples; i++) {
				tripleStore.storeTriple(resource, 2, random.nextInt(100000) * (long) Math.pow(10, random.nextInt(4)), 1,
						true);
				tripleStore.storeTriple(resource, 2 + random.nextInt(1000) + 1,
						random.nextInt(100000) * (long) Math.pow(10, random.nextInt(4)), 1, true);
			}
		}
		tripleStore.commit();

		try (Txn txn = tripleStore.getTxnManager().createReadTxn()) {
			double pred2Estimate = tripleStore.cardinality(LmdbValue.UNKNOWN_ID, 2, LmdbValue.UNKNOWN_ID, 1);
			double pred2Exact = count(
					tripleStore.getTriples(txn, LmdbValue.UNKNOWN_ID, 2, LmdbValue.UNKNOWN_ID, 1, true));
			assertTrue(pred2Estimate > 0);
			assertInRange(pred2Estimate, pred2Exact, 3);

			for (int resource = 1; resource <= nrOfResources; resource++) {
				double estimate = tripleStore.cardinality(resource, 2, LmdbValue.UNKNOWN_ID, 1);
				double exact = count(tripleStore.getTriples(txn, resource, 2, LmdbValue.UNKNOWN_ID, 1, true));
				assertTrue(estimate >= 0);
				assertInRange(estimate, exact, 3);
			}

			double obj3Estimate = tripleStore.cardinality(LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID, 3, 1);
			double obj3Exact = count(
					tripleStore.getTriples(txn, LmdbValue.UNKNOWN_ID, LmdbValue.UNKNOWN_ID, 3, 1, true));
			assertTrue(obj3Estimate >= 0);
			assertInRange(obj3Estimate, obj3Exact, 3);
		}
	}

	@AfterEach
	public void after() throws Exception {
		try {
			tripleStore.close();
		} finally {
			LmdbTestUtil.deleteDir(dataDir);
		}
	}
}
